### ISSUE TITLE
stdout not flushed

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/libcx#31] opened 2017-02-14 11:21 UTC
On a lot application we have to add either fflush(), fclose() or setvbuf() to non buffered for stdout. As else we loose at least the last bytes or the complete buffer. This is mostly the case when the stdout is sent via pipe back to the caller.
the below changset is from pgkconfig, which was needed for cmake and also for python apps.
http://trac.netlabs.org/ports/changeset/1873

See also http://trac.netlabs.org/rpm/ticket/191 for a small testcase

This might be a libc or a GCC issue with _CRT_term()

**Comment by dmik** [comment] 2017-03-21 18:54
Both LIBC and GCC `_CRT_term()` versions flush buffers as designed. It looks like this is a `socketpair() + fork()` issue. Somehow the child end of the socket pair is closed before the buffer is flushed in `_CRT_term()`. The same problem appears in git, see http://trac.netlabs.org/ports/ticket/146. We need an ultimate solution.

**Comment by dmik** [comment] 2017-03-22 14:52
The ultimate solution is to use an `atexit()` callback. See http://trac.netlabs.org/libc/ticket/374 for a detailed description. Note that the da9f5fa commit is not necessary (and should be rolled back) once the original issue is fixed in kLIBC.

**Comment by dmik** [comment] 2024-07-01 13:48
Since the fix has been moved to LIBCn (see the ticket linked above), I will roll back da9f5fa to avoid double work.

**Closed as completed** 2024-07-01 13:51 UTC
